// This file is auto-generated by generate.mjs!
import type { ComponentStory } from '@revolt/ui/components/stories';
import type { Component } from 'solid-js';
import MessageDivider from '@revolt/ui/components/design/atoms/indicators/MessageDivider.stories';
import Preloader from '@revolt/ui/components/design/atoms/indicators/Preloader.stories';
import SaveStatus from '@revolt/ui/components/design/atoms/indicators/SaveStatus.stories';
import Turbo from '@revolt/ui/components/design/atoms/indicators/Turbo.stories';
import Unreads from '@revolt/ui/components/design/atoms/indicators/Unreads.stories';
import UserStatus from '@revolt/ui/components/design/atoms/indicators/UserStatus.stories';
import Button from '@revolt/ui/components/design/atoms/inputs/Button.stories';
import Checkbox from '@revolt/ui/components/design/atoms/inputs/Checkbox.stories';
import ComboBox from '@revolt/ui/components/design/atoms/inputs/ComboBox.stories';
import Input from '@revolt/ui/components/design/atoms/inputs/Input.stories';
import MenuButton from '@revolt/ui/components/design/atoms/inputs/MenuButton.stories';
import Tabs from '@revolt/ui/components/design/atoms/inputs/Tabs.stories';
import Column from '@revolt/ui/components/design/layout/Column.stories';
import OverflowingText from '@revolt/ui/components/design/layout/OverflowingText.stories';
import Row from '@revolt/ui/components/design/layout/Row.stories';
export default {MessageDivider, Preloader, SaveStatus, Turbo, Unreads, UserStatus, Button, Checkbox, ComboBox, Input, MenuButton, Tabs, Column, OverflowingText, Row} as Record<string, ComponentStory<Component>>;