// This file is auto-generated by generate.mjs!
import type { ComponentStory } from '@revolt/ui/components/stories';
import type { Component } from 'solid-js';
import Button from '@revolt/ui/components/design/atoms/inputs/Button.stories';
export default {Button} as Record<string, ComponentStory<Component>>;